# Generated by Django 2.0.6 on 2018-07-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=40)),
                ('min_gpa', models.CharField(max_length=4)),
                ('min_year', models.CharField(max_length=4)),
                ('min_exp', models.CharField(max_length=4)),
                ('kwords', models.TextField()),
                ('req_classes', models.TextField()),
            ],
        ),
    ]
